services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'NginxProxyManager'
    restart: unless-stopped
    volumes:
      - /volume1/docker/nginx-proxy-manager/data:/data
      - /volume1/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    network_mode: host
